version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neki_ecommerce
    volumes:
      - ./mysql-data:/var/lib/mysql:Z
    networks:
      - neki-network

  redis:
    image: redis:8.0.6-alpine
    container_name: redis-dev
    ports:
      - "6380:6379"
    networks:
      - neki-network

  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: elastic-dev
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - neki-network

networks:
  neki-network:
    driver: bridge

volumes:
  es_data:
